var app=angular.module('quotes',[]);
app.controller('quoteController',function($scope)
{
	var quotes=[
	['f the world changed to love the world','Kanye West | April 28, 2018',],
	['today is the best day ever and tomorrow\'s going to be even better','Kanye West | April 28, 2018',],
	['ye vs the people @  http://kanyewest.com ','Kanye West | April 28, 2018',],
	['Trust your feelings . Stop thinking so much','Kanye West | April 28, 2018',],
	['lift yourself','Kanye West | April 28, 2018',],
	['I\'ve got a new challenge for everyone today . Pick somebody that you had an argument with that you think you hate maybe even someone you haven\'t spoken to in years and contact that person and tell them I love you','Kanye West | April 28, 2018',],
	['Lead with love','Kanye West | April 28, 2018',],
	['We got love . Agree to disagree','Kanye West | April 28, 2018',],
	['I haven\'t done enough research on conservatives to call myself or be called one . I\'m just refusing to be enslaved by monolithic thought .','Kanye West | April 27, 2018',],
	['Artist transform tragedy into beauty','Kanye West | April 26, 2018',],
	['spread love . Put more love into the universe .','Kanye West | April 26, 2018',],
	['we are more worried about what we can lose than what we feel','Kanye West | April 26, 2018',],
	['it\'s really cool to say I hate you . But it\'s not cool to say I love you . Love has a stigma','Kanye West | April 26, 2018',],
	['Instead of doing what you feel you just do what other people think you should do','Kanye West | April 26, 2018',],
	['Your conscience should allow a physical manifestation of your subconscious but right now most peoples conscious is too affected by other people\’s thoughts and it creates a disconnect from you doing what you actually feel now','Kanye West | April 26, 2018',],
	['try telling people you love them it actually feels weird at first . We\'re really good at hating each other . We have to get good at loving each other .','Kanye West | April 26, 2018',],
	['the concept of loving people has a stigma','Kanye West | April 26, 2018',],
	['my friend said he texted all his friends this morning and said I love you','Kanye West | April 26, 2018',],
	['John Legend new single on line now','Kanye West | April 26, 2018',],
	['This is year one . We can\'t ad empathy to MAGA by hating . We can only ad empathy with love and time and truly hearing all sides','Kanye West | April 26, 2018',],
	['I really appreciate this dialogue with John Legend because I\'m actually very empathetic . Im still the kid from the telethon . I feel when people think of MAGA they don\'t think of empathy .','Kanye West | April 26, 2018',],
	['if you feel something don\'t let peer pressure manipulate you','Kanye West | April 26, 2018',],
	['I tweeted the John text to show that there are people around me that disagree with me and voice their opinion . I respect everyone\'s opinion but I stand my ground .','Kanye West | April 26, 2018',],
	['People usually don\'t agree with people who don\'t agree with them','Kanye West | April 26, 2018',],
	['The world is our family','Kanye West | April 26, 2018',],
	['just think of someone you hate and try saying even to yourself that you love that person .','Kanye West | April 26, 2018',],
	['Though hate is a similar emotion to love . Hate is not the answer .  Love is .','Kanye West | April 26, 2018',],
	['that\'s the last tweet of the day . I did that one for my god-brother Puff .  Now ima go watch the Cavs .','Kanye West | April 25, 2018',],
	['Obama was in office for eight years and nothing in Chicago changed .','Kanye West | April 25, 2018',],
	['Claudio will be awesome when me and Chance build new homes in Chicago','Kanye West | April 25, 2018',],
	['Claudio Silverstein is a free thinker','Kanye West | April 25, 2018',],
	['Love is the most powerful force in the universe','Kanye West | April 25, 2018',],
	['let\'s move in love not fear','Kanye West | April 25, 2018',],
	['And any fan of me wants Ye to be Ye even when they don\'t agree because I represent the fact that they can be themselves even when people don\'t agree with them . Drops mic Yeezy shrug','Kanye West | April 25, 2018',],
	['whenever someone mentions the word "fan" to me it\'s super manipulative . It\'s like "don\'t do or say this because of your fans"  My fans are fans of themselves .','Kanye West | April 25, 2018',],
	['I want to see a tour with Nikki Minaj and Cardi B','Kanye West | April 25, 2018',],
	['I\'d like to meet with Tim Cook . I got some ideas','Kanye West | April 25, 2018',],
	['I feel calm but energized','Kanye West | April 25, 2018',],
	['need Hype Williams for Nas movie','Kanye West | April 25, 2018',],
	['I\'m sitting with Lucian discussing the future of the music industry . Lets bring in David Joseph and Frank Bridgman and Olivier Nusse .','Kanye West | April 25, 2018',],
	['I\'d like Scooter Braun to be a part of this new platform we\'re creating . Scooter is a genius .  He\'s more than a manager so is Irving .  We all need to sit together .','Kanye West | April 25, 2018',],
	['I\'m so happy to hear that Peter Thiel would like to take a meeting . I feel very optimistic about the future .','Kanye West | April 25, 2018',],
	['my MAGA hat is signed','Kanye West | April 25, 2018',],
	['I need to meet with Larry from google','Kanye West | April 25, 2018',],
	['Google supports YEEZY in ending violence in Chicago to start with','Kanye West | April 25, 2018',],
	['we\'d be a strategic investor . Not just a VC','Kanye West | April 25, 2018',],
	['I\'m 40 years old and I\'m just now becoming my parents child .','Kanye West | April 25, 2018',],
	['I\’m nice at ping pong','Kanye West | April 25, 2018',],
	['my wife just called me and she wanted me to make this clear to everyone . I don\'t agree with everything Trump does . I don\'t agree 100% with anyone but myself .','Kanye West | April 25, 2018',],
	['Yeezy VC invests in and develops food clothing shelter and communications','Kanye West | April 25, 2018',],
	['burn that excel spread sheet','Kanye West | April 25, 2018',],
	['decentralize','Kanye West | April 25, 2018',],
	['fear takes strategy   Unlearn linear thinking   Hit you with these zig zag thoughts','Kanye West | April 25, 2018',],
	['no race religion region or political party can argue with the power of love','Kanye West | April 25, 2018',],
	['When my daughter acts out she actually says afterwards I just want to hear you say I love you more .','Kanye West | April 25, 2018',],
	['I said express love more because we have love but we don\'t express it .  My friend Tmills will always say "I love you" and it used to make me feel weird to hear that . Now I tell everyone I love them .  He sparked me to start expressing love more .','Kanye West | April 25, 2018',],
	['with love I am invincible . Truth is subjective but love is the most powerful force in the world and the world needs to express more of it .','Kanye West | April 25, 2018',],
	['And also I\'m all the way out the sunken place . And I\'m not scared anymore. I\'m not scared of the media . I\'m not scared of the past and I\'m optimistic about the future . This tweet is in love not fear .','Kanye West | April 25, 2018',],
	['I love when people have their own ideas . You don\'t have to be allowed anymore . Just b e. Love who you want to love .  That\'s free thought . I\'m not even political . I\'m not a democrat or a republican','Kanye West | April 25, 2018',],
	['If your friend jumps off the bridge you don\'t have to do the same. Ye being Ye is a fight for you to be you . For people In my life the idea of Trump is pretty much a 50 50 split but I don\'t tell a Hillary supporter not to support Hillary . I love Hillary too .','Kanye West | April 25, 2018',],
	['You don\'t have to agree with trump but the mob can\'t make me not love him . We are both dragon energy . He is my brother . I love everyone . I don\'t agree with everything anyone does . That\'s what makes us individuals . And we have the right to independent thought .','Kanye West | April 25, 2018',],
	['Free thinkers don\'t fear retaliation for your thoughts .  The traditional thinkers are only using thoughts and words but they are in a mental prison . You are fre e. You\'ve already won . Feel energized . Move in love not fear . Be afraid of nothing .','Kanye West | April 25, 2018',],
	['Rocky we gotta release our songs ASAP','Kanye West | April 25, 2018',],
	['I\'m turn the Grammys into the Yammys','Kanye West | April 25, 2018',],
	['I leave my emojis bart Simpson color','Kanye West | April 25, 2018',],
	['I\'m used to the heat of independent thoughts','Kanye West | April 25, 2018',],
	['yes I said we . We the people like my brother Q Tip said on the final Tribe album that should have won the Grammy','Kanye West | April 25, 2018',],
	['when we become president we have to change the name of the plane from Air Force one to Yeezy force one','Kanye West | April 25, 2018',],
	['the Charlamagne interview just got an offer on 10 million . Yo @cthagod should we hold off for a hundred million ??? Jay Virgil Obama Trump and Mental Health .  Just a few things that were discussed . Charlamagne the new Oprah','Kanye West | April 25, 2018',],
	['adidas have been great partners and they\'ve let Yeezy be Yeezy .  This could\'ve never happened at Nike','Kanye West | April 25, 2018',],
	['the Yeezy 700 is adidas most requested shoe','Kanye West | April 25, 2018',],
	['the desert rat 500 sold 250 thousand in one hour on Coachella weekend .  Please do not try to play Yeezy or anyone who wears Yeezy . We are the future .','Kanye West | April 25, 2018',],
	['the Yeezy 350s sell 400 thousand pair in four hours . Only thing close to this is the iPhone .','Kanye West | April 25, 2018',],
	['let\’s be like water','Kanye West | April 25, 2018',],
	['oh and Ebro I love you . Ima let you finish but the Charlamagne interview is one of the best interviews of all time','Kanye West | April 25, 2018',],
	['now can I get back to my positive vibes','Kanye West | April 25, 2018',],
	['People magazine . Watch how you speak my name . You would love a pair of Yeezys . Don\'t play yourself .','Kanye West | April 25, 2018',],
	['Harvey Levin of TMZ your hearing from your future president . Let\'s be friends . Please never use the word erratic to describe a person who is economically and psychologically empowered','Kanye West | April 25, 2018',],
	['I follow the shade room .  Please never try to play Ye .','Kanye West | April 25, 2018',],
	['I am this generations Ford Hughes Jobs Disney','Kanye West | April 25, 2018',],
	['We will reach the prices I\'ve promised','Kanye West | April 25, 2018',],
	['there\'s been a lot of fake news so I just wanted to give you the facts . Yeezy will become the biggest apparel company in human history by working with the most genius level talents and creating product at an affordable price . I hired the head of supply chain from the Gap .','Kanye West | April 25, 2018',],
	['I am currently the single highest paid person in footwear . That means I make more money on shoes than Michael Jordan .','Kanye West | April 25, 2018',],
	['I\'m nobody\'s "client"','Kanye West | April 25, 2018',],
	['I no longer have a manager . I can\'t be managed','Kanye West | April 25, 2018',],
	['spread love','Kanye West | April 24, 2018',],
	['2024','Kanye West | April 24, 2018',],
	['never a master . Always a student .','Kanye West | April 24, 2018',],
	['to be great is to be misunderstood','Kanye West | April 24, 2018',],
	['dragon energy . Natural born leaders . Very instinctive . Great foresight','Kanye West | April 24, 2018',],
	['you can say anything as long as you put the right emoji next to it .','Kanye West | April 24, 2018',],
	['If your foresight is incredible   Stay stubborn to your vision','Kanye West | April 23, 2018',],
	['I\’ve always had a desire to do things people wouldn\’t even think to do','Kanye West | April 23, 2018',],
	['everyone should be their own biggest fan','Kanye West | April 23, 2018',],
	['even Prince once had an access pass','Kanye West | April 23, 2018',],
	['Prince opened up for Rick James . everybody starts some where','Kanye West | April 23, 2018',],
	['life is more exciting than the movies','Kanye West | April 23, 2018',],
	['Donald Glover is a free thinker','Kanye West | April 23, 2018',],
	['I feel like im 18 year old again when I make beats for Nas','Kanye West | April 23, 2018',],
	['new ideas will no longer be condemned by the masses . We are on the frontier of massive change . Starting from breaking out of our mental prisons .','Kanye West | April 23, 2018',],
	['we\'re evolving at warp speed','Kanye West | April 23, 2018',],
	['This is the funnest car I’ve ever driven','Kanye West | April 22, 2018',],
	['I\'m super chaaaaaarged .  Bout to take this whole thing to mars','Kanye West | April 22, 2018',],
	['I heard these are really good for the environment ','Kanye West | April 22, 2018',],
	['I really love my Tesla . I\'m in the future . Thank you Elon .','Kanye West | April 22, 2018',],
	['practice pure love','Kanye West | April 22, 2018',],
	['It’s no more baring people because they have different ideas.','Kanye West | April 22, 2018',],
	['I feel calm but energized','Kanye West | April 22, 2018',],
	['self victimization is a disease','Kanye West | April 22, 2018',],
	['there was a time when slavery was the trend and apparently that time is still upon us . But now it\'s a mentality .','Kanye West | April 22, 2018',],
	['People respect people for following the general  trend and consensus','Kanye West | April 22, 2018',],
	['We live in a time where people don’t respect people for being themselves','Kanye West | April 22, 2018',],
	['Constantly bringing up the past keeps you stuck there','Kanye West | April 22, 2018',],
	['The thought police want to suppress freedom of thought','Kanye West | April 22, 2018',],
	['we have freedom of speech but not freedom of thought','Kanye West | April 22, 2018',],
	['People demonize people and then they demonize anybody who sees anything positive in someone whose been demonized','Kanye West | April 22, 2018',],
	['The psychological zombie effect','Kanye West | April 22, 2018',],
	['Demonization has metastasized','Kanye West | April 22, 2018',],
	['the blinders are off','Kanye West | April 22, 2018',],
	['question everything','Kanye West | April 22, 2018',],
	['The more people contribute to real time global consciousness the faster we evolve','Kanye West | April 21, 2018',],
	['get past the past','Kanye West | April 21, 2018',],
	['be fearless . Express what you feel not what you\'ve been programmed to think .','Kanye West | April 21, 2018',],
	['live in love not in fear','Kanye West | April 21, 2018',],
	['I don\'t subscribe the term and concept of God fearing . That\'s a dated mentality that was used to control people . We are in the future . If God is love and love it\'s the opposite of fear then . . . to fear God makes no sense','Kanye West | April 20, 2018',],
	['only free thinkers','Kanye West | April 20, 2018',],
	['I love the way Candace Owens thinks','Kanye West | April 20, 2018',],
	['the world is our office','Kanye West | April 20, 2018',],
	['style is genderless','Kanye West | April 20, 2018',],
	['strive for universal consciousness not segregated consciousness','Kanye West | April 20, 2018',],
	['everything is so planned these days. People appreciate spontaneity and honesty .','Kanye West | April 20, 2018',],
	['iterations of ideas are how culture evolves.','Kanye West | April 20, 2018',],
	['sharing is community holding information is capitalism','Kanye West | April 20, 2018',],
	['images are limitless and words aren\'t . Words are defined','Kanye West | April 20, 2018',],
	['I don\’t believe in horizontal hierarchy . If you build a ladder too high it\’s actually most dangerous for the people at the top .','Kanye West | April 19, 2018',],
	['all you have to be is yourself','Kanye West | April 20, 2018',],
	['I need a water proof silk nylon as soon as possible .','Kanye West | April 20, 2018',],
	['people are celebrating real ideas and vibe . Not just hype','Kanye West | April 20, 2018',],
	['we need to Aman Giri the world','Kanye West | April 20, 2018',],
	['the beauty is in the imperfection(s)','Kanye West | April 19, 2018',],
	['it\'s called Kids See Ghost . That\'s the name of our group','Kanye West | April 19, 2018',],
	['me and Cudi album June 8th','Kanye West | April 19, 2018',],
	['my album is 7 songs','Kanye West | April 19, 2018',],
	['it\'s not where you take things from . It\'s where you take them to','Kanye West | April 19, 2018',],
	['we\'re all servants','Kanye West | April 19, 2018',],
	['today will be the greatest day so far . Life keeps getting better and better .','Kanye West | April 19, 2018',],
	['if you wanna see the true character of person watch the way they treat someone who can\'t do anything for them .','Kanye West | April 18, 2018',],
	['truth is my goal . Controversy is my gym . I\'ll do a hundred reps of controversy for a 6 pack of truth','Kanye West | April 18, 2018',],
	['let\'s be less concerned with ownership of ideas . It is important that ideas see the light of day even if you don\'t get the credit for them . Let\'s be less concerned with credit awards and external validation .','Kanye West | April 18, 2018',],
	['I find myself getting stuck in the idea of originality and letting my ego push me to say things like this person stole this from me and the funny thing is it\'ll be a reference I took from somewhere','Kanye West | April 18, 2018',],
	['Cars have four wheels . Hoodies have hoods . It\'s amusing to me when some one says this is an original hoodie. Bro . . . it\'s a hoodie','Kanye West | April 18, 2018',],
	['too much emphasis is put on originality . Feel free to take ideas and update them at your will all great artist take and update .','Kanye West | April 18, 2018',],
	['Be here now. Be in the moment . The now is the greatest moment of our lives and it just keeps getting better . The bad parts the boring parts the parts with high anxiety . Embrace every moment for its greatness . This is life . This is the greatest movie we will ever see .','Kanye West | April 18, 2018',],
	['There\'s love stories . Pain happiness . It\'s 3 dementional . There\'s taste touch sound . It\'s the most entertaining for of entertainment . Just being . We believe time is a man made construct . Actually time and money are both man made currency . Because you can spend them both .','Kanye West | April 18, 2018',],
	['me and my friend Anthony Schiller always ask questions about time . Is time linear ? I recently did an interview where I placed a high value on time . Everything means nothing until you make it something . You are your validator .','Kanye West | April 18, 2018',],
	['everyone will say he needs to learn how to act . At home parental acting classes are one of the first steps to us loosing who we really are to "the simulation" . Parents are our first acting coaches .','Kanye West | April 18, 2018',],
	['in life, we are all trained actors . When we\'re born we\'re ourselves and then one of the first things we\'re thought is how to act . If you see a kid screaming at a restaurant because he feels something and can\'t express himself in a conventional manner','Kanye West | April 18, 2018',],
	['just stop lying about shit . Just stop lying ."','Kanye West | April 18, 2018',],
	['I don\'t believe in the concept of an enemy . We have been conditioned to always be in competition . Stop looking for something to beat and just be . You don\'t have to do all the work . Once you start moving in love the universe will assist you','Kanye West | April 18, 2018',],
	['Don\'t follow crowds . Follow the innate feelings inside of you . Do what you feel not what you think . Thoughts have been placed in our heads to make everyone assimilate. Follow what you feel .','Kanye West | April 18, 2018',],
	['trend is always late','Kanye West | April 17, 2018',],
	['be transparent as possible . Stop setting plays . Stop playing chess with life. Make decisions based on love not fear .','Kanye West | April 17, 2018',],
	['Fear often causes people to be manipulative','Kanye West | April 17, 2018',],
	['everything you do in life stems from either fear or love','Kanye West | April 17, 2018',],
	['Sometimes you have to get rid of everything','Kanye West | April 17, 2018',],
	['distraction is the enemy of vision','Kanye West | April 17, 2018',],
	['try to avoid any contractual situation where you are held back from your ideas .','Kanye West | April 17, 2018',],
	['You have to protect your ability to create at all cost','Kanye West | April 17, 2018',],
	['As a creative your ideas are your strongest form of currency','Kanye West | April 17, 2018',],
	['often people working with the existing consciousness are jealous of those who are more in touch and they become hard-core capitalist in hopes of creating the illusion that the value of money is worth more than the value of time and friends','Kanye West | April 17, 2018',],
	['Some people have to work within the existing consciousness while some people can shift the consciousness','Kanye West | April 17, 2018',],
	['my favorite moment of walking into MSG to play Saint Pablo , I used to go to the hospital and play Lamar the album when he was learning to walk and talk again . Then we walked into the arena together','Kanye West | April 17, 2018',],
	['don\'t trade your authenticity for approval','Kanye West | April 18, 2018',]
	]
	var rand=Math.random() * quotes.length -1 ;
	console.log(quotes.length)


	console.log(rand)
	var index=Math.round(rand)
	if (index < 1)
		index*= -1
	console.log(index)
	$scope.quote=quotes[index][0];
	$scope.name=quotes[index][1];
})
